"""
Telepathy Output Core (TOC)
============================
System: Telepathy Management System (TMS)

This module is the efferent pathway for remote telepathic communication. It receives Cognitive
Response Signals (CRS) from the CNC motor gateway, and streams response fragments outward to
connected peripheral adapters via the Telepathy Domain.

Biological analogue: Peripheral Nervous System (PNS) — efferent projection from motor cortex,
carrying output signals away from the CNS outward to the periphery.

Architecture:
    TOC operates as a passive relay — no pipeline, no filtering, no cognitive logic.
    CRS fragments arrive from CNC, are immediately broadcast to all connected peripheral links.
    TOC owns no state beyond active peripheral links.
    It does not know what the response means — it only knows how to deliver it.
    If TOC goes down, CNC and TIC are unaffected — output simply stops arriving at periphery.

    Telepathy domain runs on a dedicated afferent thread — never blocks robot system cycle.
    Robot system subscription callback schedules delivery onto the telepathy thread safely.

[CNC Motor Gateway]
CRS RECEIVED
        │
        ▼
[Motor Gateway Subscriber]
        │
        ▼
[Broadcast]
        │
        ├──────────────────────────────► [Peripheral Link 1]
        ├──────────────────────────────► [Peripheral Link 2]
        └──────────────────────────────► [Peripheral Link N]

Adapters:
    Current: CLI, Web UI
    Planned: Telegram, Discord, Email, Teleops

Streaming Protocol:
    CRS fragments mirror CNC GCE stream contract:
        STREAM_LEADING     {"type": "start", "content": "<first fragment>"}
        STREAM_PROPAGATING {"type": "delta", "content": "<fragment>"}
        STREAM_TRAILING    {"type": "done",  "content": "<full response>"}
        STREAM_ANOMALY     {"type": "error", "content": "<error message>"}

Topics:
    Sub: TMS.TEXT_MOTOR_GATEWAY (std_msgs/String) — CRS JSON fragments from CNC

Message schema (inbound CRS from CNC):
    {"type": "start"|"delta"|"done"|"error", "content": "..."}

Terminology:
    CRS (Cognitive Response Signal) — structured output signal generated by CNC, carrying
                                      response fragments from the GCE stream to TOC for delivery.
    Efferent Pathway               — carries signals away from the CNS toward the periphery.
    Motor Gateway                  — ROS2 topic carrying CRS fragments from CNC to TOC.
    Peripheral Link                — active WebSocket connection from a peripheral adapter.
    Telepathy Domain               — WebSocket server — efferent channel for symbolic output.
    Teleeffector Portal            — WebSocket port — efferent output channel (TOC side).
"""

import asyncio                                              # for running telepathy domain on a dedicated neural thread, isolated from robot system cycle
import json                                                 # serialize/deserialize payloads at both boundaries
import threading                                            # owns the telepathy domain thread — keeps asyncio loop off the robot system cycle

import rclpy                                                # ROS2 Python client library — node lifecycle and spin
from rclpy.node import Node                                 # base class for all ROS2 nodes
from std_msgs.msg import String                             # ROS2 string message type for topic I/O
from websockets.exceptions import ConnectionClosedError, ConnectionClosedOK  # clean disconnect vs unexpected drop — handled separately in _on_peripheral_link
from websockets.server import ServerConnection              # type hint for peripheral link parameter

from hrs.hrm import AGi                                     # homeostatic regulation manifest namespace
from hrs.hru import hydrate_manifest                        # binds AuRoRA parameter server values into AGi constants at boot

TMS = AGi.TMS                                               # module-level alias — TMS-level constants (topic names, websocket config)

class TOC(Node):
    """
    Telepathy Output Core — Robot system node.
    
    Core for directing efferent traffic for telepathy responses from Cognitive Engine.
    Receives continous stream of CRS fragments via the motor gateway, relays the stream to all active peripheral effectors.
    Receiving -> Relaying -> Transmission
    
    Biological analogue: Peripheral Nervous System (PNS) — efferent projection from motor cortex, 
    outward transmission to peripheral effectors.
    """

    def __init__(self):
        """
        Initialize Telepathy Output Core.

        Ignites telepathy domain on a dedicated thread and opens the cognitive response signal (CRS) reception.
        Main robot system and telepathy domain never share same neural thread.
        """
        super().__init__("toc")                                                 # register this core module to robot system
        self.get_logger().info("=" * 60)                                        # TODO: Add custom logger msg for init/activate a module
        self.get_logger().info("📣 TOC — Telepathy Output Core starting…")
        self.get_logger().info("=" * 60)

        hydrate_manifest(self, system="tms")                                    # hydrate system manifest with declared paramemters

        self._active_connections = set()                                        # registry of active peripheral links to broadcast targets

        self._crs_receptor = self.create_subscription(                          # Open the gateway to receive the streams of CRS fragments
            String, TMS.TEXT_RESPONSE_GATEWAY, self._on_crs_received, 10        # signal type | neural gateway | action | buffer depth 10
        )

        # Ignite telepathy domain on its dedicated thread — never shares with main robot system processes
        self._teleeffector_cycle = asyncio.new_event_loop()                     # isolate teleeffector cycle to connect to telepathy domain lifetime
        self._teleeffector_thread = threading.Thread(                           # assign a dedicate neural thread to execute the teleeffector cycle
            target=self._teleeffector_cycle.run_forever,                        # keep teleeffector cycle running
            name="toc-teleeffector",                                            # name of teleeffector cycle
            daemon=True,                                                        # dies with main processes so no orphan thread on shutdown
        )
        self._teleeffector_thread.start()                                       # ignite teleeffector thread

        asyncio.run_coroutine_threadsafe(                                       # schedule ignition of telepathy domain on teleeffector cycle to allow safe neural thread boundary crossing
            self._ignite_telepathy_domain(), self._teleeffector_cycle
        )

        self.get_logger().info(f"✅ Response Gateway      : {TMS.TEXT_RESPONSE_GATEWAY}")    # TODO: Add custom logger msg for activated module
        self.get_logger().info(f"✅ Telepathy Domain via  : ws://{TMS.TELEPATHY_GATEWAY}:{TMS.TELEEFFCTOR_PORTAL}")
        self.get_logger().info("=" * 60)
        self.get_logger().info("📣 TOC ready — efferent pathway open")
        self.get_logger().info("=" * 60)

    async def _boot_ws_server(self) -> None:
        """
        Boot the websocket server and hold it for the node lifetime.
        Runs entirely on the toc-ws-server thread — never touches ROS2.
        """
        self._ws_server = await websockets.serve(                               # open websocket server — WebUI connects here to receive responses
            self._handle_connection,
            "0.0.0.0",
            TMS.WS_OUTPUT_PORT,
        )
        self.get_logger().info(f"✅ WebSocket server live on port {TMS.WS_OUTPUT_PORT}")
        await self._ws_server.wait_closed()                                     # hold server open until explicitly closed

    async def _handle_connection(self, websocket) -> None:
        """
        Handle one WebUI output connection for its full lifetime.
        Connection is registered as a broadcast target — receives all CRS fragments.

        Args:
            websocket: Active websocket connection from WebUI.
        """
        self._active_connections.add(websocket)                                 # register as broadcast target
        self.get_logger().info("🔗 WebUI output connected")

        try:
            await websocket.wait_closed()                                       # hold open — TOC pushes, WebUI doesn't send here
        except websockets.exceptions.ConnectionClosedOK:
            pass
        except websockets.exceptions.ConnectionClosedError as e:
            self.get_logger().warning(f"⚠️  WebUI output disconnected unexpectedly: {e}")
        finally:
            self._active_connections.discard(websocket)                         # deregister on any exit path
            self.get_logger().info("🔌 WebUI output disconnected")

    def _receive_crs(self, msg: String) -> None:
        """
        Receive a CRS fragment from the motor gateway and schedule broadcast.
        ROS2 callback — schedules onto ws loop, never blocks spin.

        Args:
            msg (String): ROS2 string message carrying serialized CRS JSON.
        """
        try:
            payload: dict = json.loads(msg.data.strip())                        # deserialize CRS payload — validate at boundary
            if not isinstance(payload, dict) or "type" not in payload:          # malformed CRS — drop silently
                return

            asyncio.run_coroutine_threadsafe(                                   # schedule broadcast on ws loop — crosses thread boundary safely
                self._broadcast(payload), self._ws_loop
            )
        except (json.JSONDecodeError, ValueError):
            self.get_logger().warning("⚠️  Malformed CRS received — dropped")

    async def _broadcast(self, payload: dict) -> None:
        """
        Broadcast a CRS fragment to all active WebUI connections.
        Runs on ws loop — never touches ROS2 spin thread.
        Dead connections are pruned on send failure.

        Args:
            payload (dict): CRS fragment — type and content fields.
        """
        if not self._active_connections:                                        # no active connections — nothing to broadcast
            return

        raw: str = json.dumps(payload)                                          # serialize once — broadcast same payload to all connections
        dead: Set = set()                                                       # collect dead connections — pruned after iteration

        for websocket in self._active_connections:
            try:
                await websocket.send(raw)                                       # relay CRS fragment to this connection
            except websockets.exceptions.ConnectionClosed:
                dead.add(websocket)                                             # mark dead — prune after iteration completes
            except Exception as e:
                self.get_logger().warning(f"⚠️  Broadcast error: {e}")
                dead.add(websocket)

        self._active_connections -= dead                                         # prune dead connections — keeps registry clean

    def destroy_node(self) -> None:
        """
        Gracefully shut down TOC — close websocket server and all active connections.
        """
        self.get_logger().info("🛑 TOC shutting down…")

        async def _close():
            for ws in list(self._active_connections):                           # close all active connections cleanly
                await ws.close()
            if hasattr(self, "_ws_server"):
                self._ws_server.close()
                await self._ws_server.wait_closed()

        future = asyncio.run_coroutine_threadsafe(_close(), self._ws_loop)
        try:
            future.result(timeout=3.0)
        except Exception:
            pass

        self._ws_loop.call_soon_threadsafe(self._ws_loop.stop)
        self._ws_thread.join(timeout=3.0)
        super().destroy_node()
        self.get_logger().info("✅ TOC shutdown complete")


def main(args=None):
    rclpy.init(args=args)
    node = TOC()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info("👋 Shutdown requested")
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
